package com.app.taskflow.services;


import com.app.taskflow.entity.Task;
import com.app.taskflow.repository.TaskRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class TaskService {

    @Autowired
    private TaskRepository taskRepository;

    public List<Task> getAllTasks() {
        return taskRepository.findAll();
    }

    public Task getTaskById(Long id) {
        return taskRepository.findById(id).orElse(null);
    }

    public Task createTask(Task task) {
        task.setTaskId(generateTaskId(task.getAssignedTo()));
        return taskRepository.save(task);
    }

    public Task updateTask(Long id, Task taskDetails) {
        Task task = taskRepository.findById(id).orElse(null);
        if (task != null) {
            task.setTitle(taskDetails.getTitle());
            task.setDescription(taskDetails.getDescription());
            task.setAssignedTo(taskDetails.getAssignedTo());
            task.setAssignedBy(taskDetails.getAssignedBy());
            task.setPriority(taskDetails.getPriority());
            task.setStartDate(taskDetails.getStartDate());
            task.setEndDate(taskDetails.getEndDate());
            task.setComment(taskDetails.getComment());
            task.setStatus(taskDetails.getStatus());
            return taskRepository.save(task);
        }
        return null;
    }

    public void deleteTask(Long id) {
        taskRepository.deleteById(id);
    }

    private String generateTaskId(String assignedTo) {
        Long autoGeneratedId = taskRepository.count() + 1; // Or any logic to get next ID
        return "TASK#" + String.format("%02d", autoGeneratedId) ;
    }
}
